name: 'datavault'
version: '1.0.0'
config-version: 2

profile: 'datavault'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


vars:
  developers_delta:
    start_date: '2022-10-01'
    end_date: '2022-10-02'
